baseURL = '/'
languageCode = 'en-us'
title = 'Hugo & Tailwind 3.0 & Pizza'
disableKinds = ["taxonomy","taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4


[params]

# favicon = "favi.png"
svginfo = '<svg  class="inline-block" xmlns="http://www.w3.org/2000/svg"  width="18" height="18" viewBox="-0.000286102 -0.00000190735 576 512"><path d="M569.517 440.013C587.975 472.007 564.806 512 527.94 512H48.054c-36.937 0-59.999-40.055-41.577-71.987L246.423 23.985c18.467-32.009 64.72-31.951 83.154 0l239.94 416.028zM288 354c-25.405 0-46 20.595-46 46s20.595 46 46 46 46-20.595 46-46-20.595-46-46-46zm-43.673-165.346l7.418 136c.347 6.364 5.609 11.346 11.982 11.346h48.546c6.373 0 11.635-4.982 11.982-11.346l7.418-136c.375-6.874-5.098-12.654-11.982-12.654h-63.383c-6.884 0-12.356 5.78-11.981 12.654z" fill="#ffffff"/></svg>'



[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

   custom_js  = ["js/cookie.js"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "hugo"
    name = "Hugo"
    url = "/hugo"
    weight = 3
   [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 5
 # [[menu.main]]
 #   identifier = "resources"
 #   name = "Resources"
 #  url = "#"
 #   weight = 2
 # [[menu.main]]
 #   identifier = "darktable"
 #  name = "darktable"
 #  url = "/darktable"
 #   parent = "resources"
 #   weight = 10
 # [[menu.main]]
 #   identifier = "rawtherapee"
 #   name = "RawTherapee & ART"
 #   url = "/rawtherapee-art"
 #   parent = "resources"
 #   weight = 20
 # [[menu.main]]
 #   identifier = "others"
 #   name = "Others"
 #   url = "/others"
 #   parent = "resources"
 #   weight = 30
 # [[menu.main]]
 #   identifier = "about"
 #   name = "About"
 #   url = "#"
 #   weight = 100
 #  [[menu.main]]
 #   identifier = "about2"
 #   name = "About"
 #   url = "/about"
 #   parent = "about"
 #   weight = 110
 # [[menu.main]]
 #   identifier = "contact"
 #   name = "Contact"
 #   url = "/contact"
 #   parent = "about"
 #   weight = 120
 # [[menu.main]]
 #   identifier = "privacy-policy"
 #   name = "Privacy Policy"
 #   url = "/privacy-policy"
 #   parent = "about"
 #   weight = 130

